### ISSUE TITLE
Add ability to filter commits based on commit type

### ISSUE THREAD

**Issue by maraisr** [brycehanscomb/semanticator#1]
In essence would like to be able to click the "commit type" on the sidebar, and filter commits. Potentially even use more visual guidance to see commit type. I hate bootstrap, but maybe use [Bootstrap Labels](http://getbootstrap.com/components/#available-variations)?

**Comment by brycehanscomb** [comment]
You can actually already filter by commit type by clicking the sidebar, exactly as you describe:

![feb 29 2016 11 55](https://cloud.githubusercontent.com/assets/2107995/13383280/6328321e-dedb-11e5-9ef9-1d2e3030e9a9.gif)

What behaviour are you getting?

**Comment by maraisr** [comment]
Hmmm - seems to be working right now.. Resolve it! Oh and https://github.com/brycehanscomb/semanticator/commit/4cc38983c9dfb8086a52fa06b14f9e220dd96b9c fixed the '^^^' i was seeing..

**Comment by brycehanscomb** [comment]
:100::100: Excellent, now closing.
